### ISSUE TITLE
Добавить автотесты

### ISSUE THREAD

**Issue by Meegera** [lisatheelsa/Your-Recipe-Assistant-#5]
На данный момент для минимально базовой готовой версии следует написать автотесты покрывающие весь готовый функционал

**Comment by lisatheelsa** [comment]
![image](https://github.com/lisatheelsa/Your-Recipe-Assistant-/assets/101552146/e781e84f-6169-40e1-ae9e-d35cd1aeeeb1)

![image](https://github.com/lisatheelsa/Your-Recipe-Assistant-/assets/101552146/007eaf62-6335-453e-8e03-fdda39f23dda)

**Comment by Meegera** [comment]
Направляю в доработку, чтобы были пройдены успешно все тесты
